---
# Build polygon-edge from source
# https://github.com/0xPolygon/polygon-edge

- name: Clone polygon-edge repository
  ansible.builtin.git:
    repo: https://github.com/0xPolygon/polygon-edge.git
    # repo: https://github.com/praetoriansentry/polygon-edge.git
    dest: /opt/polygon-edge
    version: "{{ edge_tag }}"
    recursive: true
    force: true

- name: "Build polygon-edge from commit {{ edge_tag }}"
  ansible.builtin.shell: |
    cd /opt/polygon-edge
    make build
  changed_when: false

- name: Move polygon-edge binary to /usr/local/bin
  ansible.builtin.copy:
    src: /opt/polygon-edge/polygon-edge
    dest: /usr/local/bin/
    remote_src: true
    mode: 0755
  notify:
    - Restart Edge Service

- name: Get polygon-edge version
  ansible.builtin.command: polygon-edge version
  register: edge_version_result
  changed_when: false

- name: Display polygon-edge version
  ansible.builtin.debug:
    msg: "{{ edge_version_result.stdout }}"
